name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      # curb requires libcurl dev headers
      run: sudo apt-get install libcurl4-openssl-dev

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      # see .ruby-version
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Run tests
      run: bundle exec rake
